"""Generate concept_index.py from YAML catalog files.

Scans all YAML files in formulas/catalog/ and builds a keyword→[factor IDs] mapping
based on theme, description, when_to_use, and interpretation fields.

Usage:
    python scripts/generate_concept_index.py

Output:
    vinu_tools/compute/meta/concept_index.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

CATALOG_DIR = (
    Path(__file__).resolve().parent.parent
    / "vinu_tools" / "compute" / "formulas" / "catalog"
)
OUTPUT_FILE = (
    Path(__file__).resolve().parent.parent
    / "vinu_tools" / "compute" / "meta" / "concept_index.py"
)

STOP_WORDS = {
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "can", "shall", "to", "of", "in", "for",
    "on", "at", "by", "with", "from", "as", "into", "through", "during",
    "before", "after", "above", "below", "between", "out", "off", "over",
    "under", "again", "then", "once", "here", "there", "when", "where",
    "why", "how", "all", "each", "every", "both", "few", "more", "most",
    "other", "some", "such", "no", "nor", "not", "only", "own", "same",
    "so", "than", "too", "very", "it", "its", "this", "that", "these",
    "those", "and", "but", "or", "if", "because", "up", "down", "about",
}


def tokenize(text: str) -> list[str]:
    """Extract meaningful single words and bigrams from text."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9_\s]", " ", text)
    words = [w for w in text.split() if w not in STOP_WORDS and len(w) > 1]
    tokens = set(words)
    bigrams = {f"{words[i]}_{words[i+1]}" for i in range(len(words) - 1)}
    return sorted(tokens | bigrams)


def generate_concept_index() -> dict[str, list[str]]:
    concept_index: dict[str, list[str]] = {}

    for yaml_file in sorted(CATALOG_DIR.glob("*.yaml")):
        with open(yaml_file, encoding="utf-8") as f:
            catalog = yaml.safe_load(f) or {}

        for factor_id, entry in catalog.items():
            themes = entry.get("theme", [])
            if isinstance(themes, str):
                themes = [themes]
            description = entry.get("description", "")
            when_to_use = entry.get("when_to_use", "")
            interpretation = entry.get("interpretation", "")

            text_fields = [
                " ".join(themes),
                description,
                when_to_use.replace("_", " "),
                interpretation,
            ]

            for text in text_fields:
                for token in tokenize(text):
                    concept_index.setdefault(token, [])
                    if factor_id not in concept_index[token]:
                        concept_index[token].append(factor_id)

            for theme in themes:
                if isinstance(theme, str):
                    key = theme.lower().replace(" ", "_")
                    concept_index.setdefault(key, [])
                    if factor_id not in concept_index[key]:
                        concept_index[key].append(factor_id)

    return dict(sorted(concept_index.items()))


def format_python(index: dict[str, list[str]]) -> str:
    lines = ['"""Auto-generated concept index for LLM factor discovery.',
             '',
             'Maps natural language keywords and concepts to factor IDs.',
             'Generated by scripts/generate_concept_index.py', '"""',
             '',
             'CONCEPT_INDEX: dict[str, list[str]] = {',
             ]
    for concept, factors in index.items():
        factors_str = ", ".join(f'"{f}"' for f in factors)
        lines.append(f'    "{concept}": [{factors_str}],')
    lines.append('}')
    lines.append('')
    lines.append('')
    lines.append('def find_factors(concept: str) -> list[str]:')
    lines.append('    """Look up factor IDs by concept keyword."""')
    lines.append('    return CONCEPT_INDEX.get(concept.strip().lower(), [])')
    lines.append('')
    lines.append('')
    lines.append('def search_factors(query: str) -> list[str]:')
    lines.append('    """Fuzzy search factor IDs by matching keywords in query."""')
    lines.append('    query = query.strip().lower()')
    lines.append('    results: set[str] = set()')
    lines.append('    for concept, factors in CONCEPT_INDEX.items():')
    lines.append('        if query in concept or concept in query:')
    lines.append('            results.update(factors)')
    lines.append('    return sorted(results)')
    lines.append('')
    return '\n'.join(lines)


def main():
    print("Generating concept index from YAML catalogs...")
    index = generate_concept_index()

    code = format_python(index)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(code)

    print(f"  → {len(index)} concepts mapping to factor IDs")
    print(f"  → Written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
