"""Geopolitical place/country mappings (Fincept NER)."""

COUNTRY_MAP = {
    "beijing": "CN",
    "shanghai": "CN",
    "china": "CN",
    "chinese": "CN",
    "moscow": "RU",
    "russia": "RU",
    "russian": "RU",
    "kremlin": "RU",
    "washington": "US",
    "white house": "US",
    "united states": "US",
    "u.s.": "US",
    "usa": "US",
    "american": "US",
    "london": "GB",
    "uk": "GB",
    "britain": "GB",
    "british": "GB",
    "brussels": "EU",
    "european union": "EU",
    "eu": "EU",
    "tokyo": "JP",
    "japan": "JP",
    "japanese": "JP",
    "india": "IN",
    "indian": "IN",
    "gaza": "PS",
    "israel": "IL",
    "israeli": "IL",
    "ukraine": "UA",
    "ukrainian": "UA",
    "taiwan": "TW",
    "taiwanese": "TW",
    "iran": "IR",
    "iranian": "IR",
    "saudi": "SA",
    "riyadh": "SA",
}
