"""Known figure name mappings (Fincept NER)."""

PEOPLE_MAP = {
    "powell": "Jerome Powell",
    "jerome powell": "Jerome Powell",
    "musk": "Elon Musk",
    "elon musk": "Elon Musk",
    "yellen": "Janet Yellen",
    "janet yellen": "Janet Yellen",
    "bezos": "Jeff Bezos",
    "jeff bezos": "Jeff Bezos",
    "cook": "Tim Cook",
    "tim cook": "Tim Cook",
    "zuckerberg": "Mark Zuckerberg",
    "mark zuckerberg": "Mark Zuckerberg",
    "pichai": "Sundar Pichai",
    "sundar pichai": "Sundar Pichai",
    "dimon": "Jamie Dimon",
    "jamie dimon": "Jamie Dimon",
    "lagarde": "Christine Lagarde",
    "christina lagarde": "Christine Lagarde",
    "christine lagarde": "Christine Lagarde",
    "xi jinping": "Xi Jinping",
    "putin": "Vladimir Putin",
    "vladimir putin": "Vladimir Putin",
    "trump": "Donald Trump",
    "donald trump": "Donald Trump",
    "biden": "Joe Biden",
    "joe biden": "Joe Biden",
}
